const ErrorHandler = require("../utils/errorhandler");
const BackendLog = require('../models/backendLog');


const errorHandler = async (error, req, res, next) => {

    console.log(error)

    if (error.name == 'CastError') {
        const message = `Resource Not Found Invalid : ${error.path}`
        err = new ErrorHandler(message, 400)
    }

    if (error.statusCode === 11000) {
        const message = `Duplicate ${Object.keys(error.keyValue)} Entered`
        error = new ErrorHandler(message, 400)
    }

    if (error.message === "Cannot read properties of undefined (reading 'replace')") {
        error.message = "Kindly fill all information";
        error.statusCode = 400;
    }

        // if error generated by by server regardless of user than store on db

    if(error.statusCode === 500){

        
        const log = new BackendLog({
            functionName: error.functionName,
            controllerName: error.controllerName,
            modelName: error.modelName,
            status: error.statusCode,
            errorMessage: error.message,
        })
    
        await log.save();

        console.log(log)

    }

    return res.status(error.statusCode).json({ success: false, message: error.message, error: error.message  , status : error.statusCode });

}

module.exports = errorHandler