
import React, { useRef, useEffect } from "react";
import { Button } from "react-bootstrap";
import ReactToPrint from "react-to-print";
import { Container, Row, Col, Table } from 'react-bootstrap';

import './Report.css'; // Import the external CSS file

import Sidenav from '../components/Sidenav/Sidenav'
import { Box } from '@mui/material';
import Navbar from '../components/Navbar/Navbar';
import '../pages/Dash.css';
import { useSelector, useDispatch } from "react-redux"
import { getinventoryReport, clearErrors } from "../actions/reportAction";
import { useAlert } from "react-alert";
import Loader from '../components/loader/Loader'



export default function InventoryReport() {
    let componentRef = useRef();


    return (
        <>
            <Navbar />
            <Box height={90} />
            <Box sx={{ display: 'flex' }}>
                <Sidenav />
                <Box component="main" sx={{ flexGrow: 1, p: 3, }}>
                    <div >
                        <ReactToPrint
                            trigger={() => <Button style={{
                                background: 'darkBlue',
                                border: '2px solid #ccc',
                                borderRadius: '12px',
                                padding: '10px 20px',
                                cursor: 'pointer',
                                transition: 'all .2s ease-in-out',
                                '&:hover': {
                                    background: 'black',
                                },
                            }} >Print this out!</Button>}
                            content={() => componentRef}
                        />

                        <InventoryReportPage ref={(el) => (componentRef = el)} />

                    </div>
                </Box>
            </Box>
        </>
    );
}



const InventoryReportPage = React.forwardRef((props, ref) => {
    const { user } = useSelector((state) => state.user);
    const { report: inventoryReportData, loading, error } = useSelector((state) => state.report);

    const alert = useAlert();
    const dispatch = useDispatch();

    useEffect(() => {
        if (error) {
            alert.error(error);
            dispatch(clearErrors())
        }
        dispatch(getinventoryReport());


    }, [dispatch, alert, error])







    return (
        <> {loading ? <Loader /> :
            <div ref={ref} style={{ marginTop: '2%' }} >
                <div className="container mt-4">
                    <h1 className="display-3 text-center text-uppercase font-weight-bold">
                        Inventory Report
                    </h1>
                    <div className="container mt-2">
                        <p className="display-7 text-center text-uppercase font-weight-bold">
                            By Eccomerce
                        </p>
                    </div>
                </div>


                <div className="mt-5" style={{ marginTop: '10%', marginLeft: "10%", marginRight: "10%", padding: "2%" }}>
                    <Row>
                        <Col xs={12} md={6}>
                            <p className="sales-info text-uppercase" style={{ fontSize: '14px', fontWeight: 'bold', fontStyle: 'Arial', color: 'black' }}>
                                Average Product stock: {inventoryReportData && inventoryReportData.averageProductStock}
                            </p>
                        </Col>
                        <Col xs={12} md={6} className="text-end">
                            <p className="sales-info text-uppercase" style={{ fontSize: '14px', fontWeight: 'bold', fontStyle: 'Arial', color: 'grey' }}>
                                Date: {new Date().toLocaleDateString()}
                            </p>
                        </Col>
                    </Row>
                    <Row>
                        <Col xs={12} md={6}>
                            <p className="sales-info text-uppercase" style={{ fontSize: '14px', fontStyle: 'Arial', color: 'black' }}>
                                Generated By: {user.name}
                            </p>
                        </Col>
                    </Row>
                </div>


                <div style={{ marginLeft: "10%", marginRight: "10%", padding: "2%" }}>
                    <Row >
                        <Col xs={12}>
                            <Table striped bordered hover responsive style={{ background: "#001f3f", color: "white", border: "1px solid #001f3f", fontSize: "16px" }}>
                                <thead >
                                    <tr >
                                        <th style={{ background: "blue", color: "white", textAlign: 'center' }}>Product Name</th>
                                        <th style={{ background: "blue", color: "white", textAlign: 'center' }}>Product Description</th>
                                        <th style={{ background: "blue", color: "white", textAlign: 'center' }}>Product Price</th>
                                        <th style={{ background: "blue", color: "white", textAlign: 'center' }}>Product Stock</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    {inventoryReportData && inventoryReportData.stockLevels && inventoryReportData.stockLevels.map((data, index) => (
                                        <tr key={index}>
                                            <td style={{ textAlign: 'center', background: data.product.stock < 5 ? 'red' : '', color: data.product.stock < 5 ? 'white' : 'black' }}>{data.product.name}</td>
                                            <td style={{ textAlign: 'center', background: data.product.stock < 5 ? 'red' : '', color: data.product.stock < 5 ? 'white' : 'black' }}>{data.product.description}</td>
                                            <td style={{ textAlign: 'center', background: data.product.stock < 5 ? 'red' : '', color: data.product.stock < 5 ? 'white' : 'black' }}>{data.product.price}</td>
                                            <td style={{ textAlign: 'center', background: data.product.stock < 5 ? 'red' : '', color: data.product.stock < 5 ? 'white' : 'black' }}>{data.product.stock}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </Table>
                        </Col>
                    </Row>
                </div>





            </div>
        }</>


    );
});

