export const REPORT_DATA_REQUEST = "REPORT_DATA_REQUEST";
export const REPORT_DATA_SUCCESS = "REPORT_DATA_SUCCESS";
export const REPORT_DATA_RESET = "REPORT_DATA_RESET";
export const REPORT_DATA_FAIL = "REPORT_DATA_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";