export const CHANGE_DARK_MODE = "CHANGE_DARK_MODE";

export const CHANGE_DOPEN = "CHANGE_DOPEN";

export const DASHBOARD_DATA_REQUEST = "DASHBOARD_DATA_REQUEST"

export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS"

export const DASHBOARD_DATA_FAIL = "DASHBOARD_DATA_FAIL"